name: Continuous Integration (CI)
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: "gradle"
      - name: Make gradle wrapper executable
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test
  pmd:
    permissions:
      contents: read  # for pmd/pmd-github-action to determine modified files
      pull-requests: read  # for pmd/pmd-github-action to query PRs
    name: Run PMD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: "gradle"
      - name: Run PMD
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'rulesets/hello.xml'
